# Generated by Django 3.1.5 on 2021-01-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_auto_20210110_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bucket',
        ),
    ]
